# Generated by Django 5.2.4 on 2025-08-01 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code de réduction')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Pourcentage'), ('FIXED', 'Montant fixe')], max_length=20, verbose_name='Type de réduction')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valeur de la réduction')),
                ('max_uses', models.IntegerField(default=1, verbose_name='Utilisations maximales')),
                ('used_count', models.IntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('max_uses_per_user', models.IntegerField(default=1, verbose_name='Utilisations max par utilisateur')),
                ('valid_from', models.DateTimeField(verbose_name='Valide à partir de')),
                ('valid_until', models.DateTimeField(verbose_name="Valide jusqu'à")),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant minimum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Code de réduction',
                'verbose_name_plural': 'Codes de réduction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant de la TVA')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('issue_date', models.DateField(verbose_name="Date d'émission")),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyée'), ('PAID', 'Payée'), ('OVERDUE', 'En retard'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Invoice ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('SUBSCRIPTION', 'Abonnement'), ('EVENT', 'Événement ponctuel'), ('REFUND', 'Remboursement')], max_length=20, verbose_name='Type de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Payment Intent ID')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Charge ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours'), ('SUCCEEDED', 'Réussi'), ('FAILED', 'Échec'), ('CANCELLED', 'Annulé'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('failure_reason', models.TextField(blank=True, verbose_name="Raison de l'échec")),
                ('refund_reason', models.TextField(blank=True, verbose_name='Raison du remboursement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(max_length=100, verbose_name='Stripe Payment Method ID')),
                ('stripe_customer_id', models.CharField(max_length=100, verbose_name='Stripe Customer ID')),
                ('card_brand', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover'), ('diners', 'Diners Club'), ('jcb', 'JCB'), ('unionpay', 'UnionPay'), ('unknown', 'Inconnue')], default='unknown', max_length=20, verbose_name='Marque de la carte')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='4 derniers chiffres')),
                ('card_exp_month', models.IntegerField(blank=True, null=True, verbose_name="Mois d'expiration")),
                ('card_exp_year', models.IntegerField(blank=True, null=True, verbose_name="Année d'expiration")),
                ('is_default', models.BooleanField(default=False, verbose_name='Méthode par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renouvellement automatique')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('CANCELLED', 'Annulé'), ('EXPIRED', 'Expiré'), ('PENDING', 'En attente'), ('FAILED', 'Échec')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('events_used', models.IntegerField(default=0, verbose_name='Événements utilisés')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Subscription ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Customer ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du plan')),
                ('plan_type', models.CharField(choices=[('TICKET', 'Ticket unique'), ('MONTHLY_1', 'Abonnement 1 mois'), ('MONTHLY_3', 'Abonnement 3 mois'), ('MONTHLY_6', 'Abonnement 6 mois')], max_length=20, verbose_name='Type de plan')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('monthly_equivalent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix équivalent mensuel')),
                ('duration_months', models.IntegerField(default=1, verbose_name='Durée en mois')),
                ('events_included', models.IntegerField(default=1, help_text="Nombre d'événements inclus ou -1 pour illimité", verbose_name='Événements inclus')),
                ('discount_percentage', models.IntegerField(default=0, verbose_name='Pourcentage de réduction')),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Price ID')),
                ('stripe_product_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Product ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Plan populaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['duration_months', 'price'],
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant de la réduction appliquée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'utilisation")),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='payments.discount')),
            ],
            options={
                'verbose_name': 'Utilisation de code de réduction',
                'verbose_name_plural': 'Utilisations de codes de réduction',
                'ordering': ['-created_at'],
            },
        ),
    ]
