# Generated by Django 5.2.4 on 2025-08-01 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
                ('code_type', models.CharField(choices=[('EMAIL_VERIFICATION', 'Vérification email'), ('PASSWORD_RESET', 'Réinitialisation mot de passe'), ('PHONE_VERIFICATION', 'Vérification téléphone')], max_length=20, verbose_name='Type de code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utilisé le')),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code de vérification',
                'verbose_name_plural': 'Codes de vérification',
                'ordering': ['-created_at'],
            },
        ),
    ]
