# Generated by Django 5.2.4 on 2025-08-06 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalitytestresult',
            name='detailed_disc_scores',
            field=models.JSONField(default=dict, verbose_name='Scores DISC détaillés'),
        ),
        migrations.AddField(
            model_name='personalitytestresult',
            name='detailed_mbti_scores',
            field=models.JSONField(default=dict, verbose_name='Scores MBTI détaillés'),
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('PERSONAL_INFO', 'Informations personnelles'), ('PERSONALITY_TEST', 'Test de personnalité'), ('PASSION_SELECTION', 'Sélection des passions'), ('COMPLETED', 'Terminé')], default='PERSONAL_INFO', max_length=20, verbose_name='Étape actuelle')),
                ('completed_steps', models.JSONField(default=list, verbose_name='Étapes complétées')),
                ('temp_data', models.JSONField(blank=True, default=dict, verbose_name='Données temporaires')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Commencé le')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progrès onboarding',
                'verbose_name_plural': 'Progrès onboarding',
            },
        ),
        migrations.CreateModel(
            name='PersonalityTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True, verbose_name='ID de session')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Commencé le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Durée en secondes')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Test complété')),
                ('current_question', models.IntegerField(default=0, verbose_name='Question actuelle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personality_test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de test de personnalité',
                'verbose_name_plural': 'Sessions de test de personnalité',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='personalitytestresult',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='users.personalitytestsession'),
        ),
        migrations.CreateModel(
            name='PersonalityTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(verbose_name='ID de la question')),
                ('question_text', models.TextField(verbose_name='Texte de la question')),
                ('answer_index', models.IntegerField(verbose_name='Index de la réponse choisie')),
                ('answer_text', models.TextField(verbose_name='Texte de la réponse')),
                ('mbti_scores', models.JSONField(default=dict, verbose_name='Scores MBTI')),
                ('disc_scores', models.JSONField(default=dict, verbose_name='Scores DISC')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Répondu le')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.personalitytestsession')),
            ],
            options={
                'verbose_name': 'Réponse au test de personnalité',
                'verbose_name_plural': 'Réponses au test de personnalité',
                'unique_together': {('session', 'question_id')},
            },
        ),
    ]
