# Generated by Django 5.2.4 on 2025-08-06 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_personalitytestresult_detailed_disc_scores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_interests', models.JSONField(default=list, help_text="Liste des centres d'intérêt sélectionnés (id, name, color)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Centres d'intérêt utilisateur",
                'verbose_name_plural': "Centres d'intérêt utilisateurs",
            },
        ),
    ]
