# Generated by Django 5.2.4 on 2025-08-06 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userinterests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200, verbose_name="Nom de l'activité")),
                ('activity_description', models.TextField(blank=True, verbose_name='Description')),
                ('reservation_date', models.DateField(verbose_name='Date de réservation')),
                ('reservation_time', models.TimeField(default='20:00', verbose_name='Heure')),
                ('venue_name', models.CharField(default='Paris', max_length=200, verbose_name='Nom du lieu')),
                ('venue_address', models.TextField(blank=True, verbose_name='Adresse complète')),
                ('price_plan', models.CharField(max_length=100, verbose_name='Plan tarifaire')),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée'), ('COMPLETED', 'Terminée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200, verbose_name='Stripe Payment Intent ID')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('participants_count', models.PositiveIntegerField(default=1, verbose_name='Nombre de participants')),
                ('special_requests', models.TextField(blank=True, verbose_name='Demandes spéciales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('cancellation_deadline', models.DateTimeField(blank=True, null=True, verbose_name="Limite d'annulation")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['reservation_date', 'reservation_time'],
            },
        ),
    ]
