# Generated by Django 5.2.4 on 2025-08-06 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du groupe')),
                ('event_date', models.DateField(verbose_name="Date de l'événement")),
                ('activity_name', models.CharField(max_length=200, verbose_name="Nom de l'activité")),
                ('meeting_point_name', models.CharField(blank=True, max_length=200, verbose_name='Lieu de rendez-vous')),
                ('meeting_point_address', models.TextField(blank=True, verbose_name='Adresse du rendez-vous')),
                ('meeting_time', models.TimeField(default='20:00', verbose_name='Heure de rendez-vous')),
                ('location_reveal_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de révélation du lieu')),
                ('max_participants', models.PositiveIntegerField(default=6, verbose_name='Nombre max de participants')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Groupe confirmé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': "Groupe d'événement",
                'verbose_name_plural': "Groupes d'événements",
                'ordering': ['event_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Rejoint le')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.eventgroup')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_membership', to='users.reservation')),
            ],
            options={
                'verbose_name': 'Appartenance au groupe',
                'verbose_name_plural': 'Appartenances aux groupes',
                'unique_together': {('reservation', 'group')},
            },
        ),
    ]
