# Generated by Django 5.2.4 on 2025-08-06 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_eventgroup_groupmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du ticket')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('USED', 'Utilisé'), ('EXPIRED', 'Expiré')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('source', models.CharField(choices=[('CANCELLATION', 'Annulation de réservation'), ('REFUND', 'Remboursement'), ('PROMOTIONAL', 'Promotionnel'), ('GIFT', 'Cadeau')], max_length=20, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utilisé le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('original_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tickets', to='users.reservation')),
                ('used_for_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_tickets', to='users.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket utilisateur',
                'verbose_name_plural': 'Tickets utilisateur',
                'ordering': ['-created_at'],
            },
        ),
    ]
