# Generated by Django 5.2.4 on 2025-08-06 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(max_length=254, verbose_name="Email de l'invité")),
                ('invitation_token', models.CharField(max_length=100, unique=True, verbose_name="Token d'invitation")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('EXPIRED', 'Expirée'), ('USED', 'Utilisée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('message', models.TextField(blank=True, verbose_name='Message personnalisé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepté le')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utilisé le')),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='users.reservation')),
            ],
            options={
                'verbose_name': "Invitation d'ami",
                'verbose_name_plural': "Invitations d'amis",
                'ordering': ['-created_at'],
                'unique_together': {('inviter', 'invited_email', 'reservation')},
            },
        ),
    ]
