# Generated by Django 5.2.4 on 2025-08-10 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_friendinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitation_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_user_profile', to='users.friendinvitation'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_invited_user',
            field=models.BooleanField(default=False, verbose_name='Utilisateur invité'),
        ),
    ]
