# Generated by Django 5.2.4 on 2025-08-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_invitation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin abonnement'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_events_used',
            field=models.IntegerField(default=0, verbose_name='Événements utilisés ce mois'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_last_reset',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière remise à zéro'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Début abonnement'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('NONE', 'Aucun abonnement'), ('MONTHLY_1', 'Abonnement 1 mois'), ('MONTHLY_3', 'Abonnement 3 mois'), ('MONTHLY_6', 'Abonnement 6 mois')], default='NONE', max_length=10, verbose_name="Type d'abonnement"),
        ),
    ]
