# Generated by Django 5.2.4 on 2025-08-11 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_events_used',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_last_reset',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_start_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('FREE', 'Gratuit'), ('TICKET', 'Ticket'), ('SUBSCRIPTION', 'Abonnement')], default='FREE', max_length=20, verbose_name='Type de compte'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_active_subscription',
            field=models.BooleanField(default=False, verbose_name='Abonnement actif'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('MONTHLY', '1 mois'), ('QUARTERLY', '3 mois'), ('SEMESTRIAL', '6 mois')], max_length=20, verbose_name="Type d'abonnement")),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix payé')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=200, verbose_name='Stripe Subscription ID')),
                ('reservations_used', models.PositiveIntegerField(default=0, verbose_name='Réservations utilisées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Annulé le')),
                ('is_test_mode', models.BooleanField(default=False, verbose_name='Mode test')),
                ('current_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_used', to='users.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement utilisateur',
                'verbose_name_plural': 'Abonnements utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
